version: "3"

services:
  acme_loan_registration:
    build:
      context: .
      args:
        APPLICATION_NAME: acme-loan-registration
    image: docker.acme.com/acme-loan-registration:latest
    container_name: acme_loan_registration_01
    hostname: loan-registration
    domainname: acme.com
    ports:
      - 8001:8080
    networks:
      acme:

networks:
  acme:
    external:
      name: acme
