CREATE TABLE REGISTER_LOAN
( ID                                    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY
, EVENT_ID                              VARCHAR2(36 CHAR)         NOT NULL
, PERSON_ID                             VARCHAR2(36 CHAR)         NOT NULL
, AMOUNT                                DOUBLE(19)                NOT NULL
, REGISTERED_TIMESTAMP                  TIMESTAMP                 NOT NULL
, ENTITLED_TIMESTAMP                    TIMESTAMP
, REJECTED_TIMESTAMP                    TIMESTAMP
, CONSTRAINT REGISTER_LOAN_PK           PRIMARY KEY (ID)
, CONSTRAINT REGISTER_LOAN_EVENT_ID_UC  UNIQUE (EVENT_ID)
);